// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserModelApp.Model;

#nullable disable

namespace EF_Core_Model.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260418222147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UserRoles_Updated")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserModelApp.Model.Projects", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects", "UserRoles_Updated");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budget = 2500m,
                            ProjectName = "Inventory System"
                        },
                        new
                        {
                            ProjectId = 2,
                            Budget = 1800m,
                            ProjectName = "Bug Tracker"
                        });
                });

            modelBuilder.Entity("UserModelApp.Model.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "UserRoles_Updated");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Head Programmer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Debugger"
                        });
                });

            modelBuilder.Entity("UserModelApp.Model.UserProjects", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProjects", "UserRoles_Updated");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ProjectId = 1,
                            AssignedOn = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursPerWeek = 20
                        },
                        new
                        {
                            UserId = 2,
                            ProjectId = 2,
                            AssignedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursPerWeek = 15
                        });
                });

            modelBuilder.Entity("UserModelApp.Model.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Department")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "UserRoles_Updated");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Department = "Engineering",
                            Name = "Daniel Gray"
                        },
                        new
                        {
                            UserId = 2,
                            Department = "QA",
                            Name = "Neil Jones"
                        });
                });

            modelBuilder.Entity("UserModelApp.Model.WorkItems", b =>
                {
                    b.Property<int>("WorkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkItemId"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("WorkItemId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkItems", "UserRoles_Updated");

                    b.HasData(
                        new
                        {
                            WorkItemId = 1,
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Build Login"
                        },
                        new
                        {
                            WorkItemId = 2,
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Fix Search Bug"
                        });
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("RolesRoleId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UsersRoles", "UserRoles_Updated");

                    b.HasData(
                        new
                        {
                            RolesRoleId = 1,
                            UsersUserId = 1
                        },
                        new
                        {
                            RolesRoleId = 2,
                            UsersUserId = 2
                        });
                });

            modelBuilder.Entity("UserModelApp.Model.UserProjects", b =>
                {
                    b.HasOne("UserModelApp.Model.Projects", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserModelApp.Model.Users", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserModelApp.Model.WorkItems", b =>
                {
                    b.HasOne("UserModelApp.Model.Projects", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.HasOne("UserModelApp.Model.Roles", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserModelApp.Model.Users", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserModelApp.Model.Projects", b =>
                {
                    b.Navigation("UserProjects");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("UserModelApp.Model.Users", b =>
                {
                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
